server:
  port: 80

spring:
  application:
    name: "shop_a"

  thymeleaf:
    cache: false

  ###############################################
  # DevTools Setting
  ###############################################
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  ###############################################
  # MySQL Setting
  ###############################################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 201945022

  ###############################################
  # JPA Setting
  ###############################################
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update  # update, create, create-drop, none, validate
#      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  ###############################################
  # Security Setting
  ###############################################
  security:
    user:
      name: user
      password: 1111

  ###############################################
  # Servlet Setting
  ###############################################
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

itemImgLocation: ~/Documents/WorkSpace/IDEA/SpringFrameworkImg/item
uploadPath: file:///~/Documents/WorkSpace/IDEA/SpringFrameworkImg

###############################################
# Logging
###############################################
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace